spring:
  application:
    name: msvc-producto
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true

  # --- Añadimos aquí SpringDoc/OpenAPI ---
  springdoc:
    api-docs:
      path: /v3/api-docs  # Ruta para la API Docs
    swagger-ui:
      path: /swagger-ui.html  # Ruta para la interfaz de Swagger
