spring:
  config:
    import: "configserver:http://localhost:8888"
  application:
    name: msvc-venta
  cloud:
    config:
      fail-fast: true

  sql:
    init:
      mode: always

  # Configuración de Swagger
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
