spring:
  cloud:
    gateway:
      routes:
        - id: producto
          uri: lb://MSVC-PRODUCTO
          predicates:
            - Path=/api/v1/producto/**
        - id: venta
          uri: lb://MSVC-VENTA
          predicates:
            - Path=/api/v1/ventas/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
