server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ventas
          uri: http://localhost:8090
          predicates:             
            - Path=/api/v1/ventas/**
        - id: productos
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/productos/**
        
eureka:
  cliente:
    register-with-eureka: false
 
        